### ISSUE TITLE
Cannot use as a Unity package

### ISSUE THREAD

**Issue by rfadeev** [nailuj05/FusionWater#2]
Hi,

Tried to use the repository as a local Unity package and got following error:

```
An error occurred while resolving packages:
  Folder [C:\Unity Projects\FusionWater\Packages] contains invalid packages:
    Manifest [C:\Unity Projects\FusionWater\Packages\FusionWater-main\package.json] is invalid:
      `unityRelease` attribute is set to `0b5` but `unity` attribute is not set.

A re-import of the project may be required to fix the issue or a manual modification of C:/Unity Projects/FusionWater/Packages/manifest.json file.
```

What is the minimum Unity version for the project?

Tried to add `"unity": "2021.2",` to the manifest and used Unity 2021.2.0b5: project can be opened but references to scripts in the scenes seem lost, at least inspector shows the warning. This is probably caused by missing assembly definition file.

Also there are missing material references for prefab instances in the scenes. Like in "MultipleFluids" scene it shows missing material for "Complex" and "Complex (1)" prefab instances.

**Comment by nailuj05** [comment]
I will look into it and recompile the package. For the mean time you can download the package via github directly as a zip and import that into Unity.

Thank you for contributing :)

**Comment by rfadeev** [comment]
Great, thank you! Sad that it cannot be used as Unity Package Manager package anymore.

I player around with example scenes and observed following (Unity 2019.4.18f1):
* All three scenes have missing script on "Main Camera" game object
* "BoatExample" scene gets boat fall through water in playmode
* "Water example" scene gets two cubes fall through water in playmode

**Comment by nailuj05** [comment]
Yeah, I will look into getting a proper package manifest setup soon. The script on the main camera can be deleted. That is the Universal Camera Addon Script, that is requierd on any URP Camera. Should not cause and error though. 

I wasn't able to reproduce your error with the objects falling through though.
I *guess* it might be because you have collisions between "Water" and "Default" Layers turned off.

Maybe look into your physics settings if you can change it or assign the water to a different layer.

**Comment by nailuj05** [comment]
Interesting. Can you maybe send me the scene or project in which it was happening?
Would help me trying tl reproduce it.

**Comment by nailuj05** [comment]
Thank you for pointing it out. Otherwise I wouldn't have noticed, that I forgot to swap out the collision meshes for the non-blender meshes! :)
