### ISSUE TITLE
Can't add script component

### ISSUE THREAD

**Issue by xitxat** [nailuj05/FusionWater#4]
When dragging Fluid script to water plane I get a "Can't add script " error ~ because the script class can't be found.
Also from inside the BoatEx ~the associated script cant be loaded

Unity 2021.3.8f1

**Comment by nailuj05** [comment]
Hi thank you for opening an issue. I was not able to recreate the issue. Would you mind sending me a copy of the Unity Project or *a Unity Project* where this happens? Do you have any compile errors on the scripts?
